apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nq2vy48zt-go
  janus-idp.io/tekton: nq2vy48zt-go
  backstage.io/kubernetes-id: nq2vy48zt-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nq2vy48zt-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
